package com.dreamTimes.dao;

import com.dreamTimes.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);


    /**
     * 根据userID和productID判断是否存在购物车商品
     * @param userId
     * @param productId
     * @return
     */
    Cart findCartByUserIdAndProductId(@Param("userId") Integer userId,
                                     @Param("productId") Integer productId);


    /**
     * 根据userID查找相关的商品项
     * @param userId
     * @return
     */
    List<Cart> findCartByUserId(@Param("userId") Integer userId);
}