package com.dreamTimes.dao;

import com.dreamTimes.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);


    /**
     * 根据用户id查询所有的订单
     * @param userId
     * @return
     */
    List<Order> findAllOrderByUserId(Integer userId);


    /**
     * 根据订单号查询订单
     * @return
     */
    Order selectOrderByOrderNO(@Param("userId") Integer userId,
                               @Param("orderNo") Long orderNo);


    /**
     * 根据订单号进行搜索
     * @return
     */
    List<Order> findOrderByOrderNO(Long orderNo);

    /**
     * 根据创建订单时间和订单的状态进行查询
     */
    List<Order> findOrderByCreateTimeAndStatus(@Param("status") Integer status,
                                               @Param("time") String time);
}