package com.dreamTimes.dao;

import com.dreamTimes.pojo.Shipping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shipping record);


    /**
     * 根据用户id和shippingid进行查询
     * @param userId
     * @param shippingId
     * @return
     */
    Shipping selectByUidAndShippingId(@Param("userId") Integer userId,
                                      @Param("shippingId") Integer shippingId);


    /**
     * 根据用户id进行查询
     * @param userId
     * @return
     */
    List<Shipping> selectByUid(Integer userId);
}